workflows:
  flutter-android-build-workflow:
    name: Flutter Android Build Workflow
    instance_type: mac_mini_m1
    max_build_duration: 30
    
environment:
      java: 17
      android_signing:
        - power_of_one_android_key
      groups:
        - google_credentials
      vars:
        PACKAGE_NAME: 'com.power_of_one.basketball'
        GOOGLE_PLAY_TRACK: 'internal'
      flutter: stable
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache          # Dart cache
        - $HOME/.gradle/caches              # Gradle cache
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Flutter analyze
        script: |
          flutter analyze
        ignore_failure: true
      # - name: Flutter unit tests
      #   script: |
      #     flutter test
      #   ignore_failure: true
      - name: Build AAB with Flutter
        script: |
          BUILD_NUMBER=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME") + 1))
          flutter build appbundle --release \
            --build-name=1.1.$BUILD_NUMBER \
            --build-number=$BUILD_NUMBER
    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log


  flutter-deploy-to-android-play-console:
    name: Deploy Flutter AAB to Google Play Console
    instance_type: mac_mini_m1
    max_build_duration: 30
    triggering:
      workflow_run:
    triggering:
      events:
        - tag
      cancel_previous_builds: true
    environment:
      java: 17
      android_signing:
        - power_of_one_android_key
      groups:
        - google_credentials
      vars:
        PACKAGE_NAME: 'com.power_of_one.basketball'
        GOOGLE_PLAY_TRACK: 'internal'
      flutter: stable
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache          # Dart cache
        - $HOME/.gradle/caches              # Gradle cache
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Flutter analyze
        script: |
          flutter analyze
        ignore_failure: true
      # - name: Flutter unit tests
      #   script: |
      #     flutter test
      #   ignore_failure: true
      - name: Build AAB with Flutter
        script: |
          BUILD_NUMBER=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME") + 1))
          flutter build appbundle --release \
            --build-name=1.1.$BUILD_NUMBER \
            --build-number=$BUILD_NUMBER
    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - powell.anthony.e@gmail.com
        notify:
          success: true
          failure: false
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: $GOOGLE_PLAY_TRACK
        submit_as_draft: true


  ios-build-workflow:
    name: iOS Build Workflow
    instance_type: mac_mini_m1
    max_build_duration: 30
    integrations:
      app_store_connect: Power of One
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.powerofone.basketball
      flutter: stable
      xcode: latest # <-- set to specific version e.g. 14.3, 15.0 to avoid unexpected updates.
      cocoapods: default
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter analyze
        script: |
          flutter analyze
        ignore_failure: true
      # - name: Flutter unit tests
      #   script: |
      #     flutter test
      #   ignore_failure: true
      - name: Flutter build ipa and automatic versioning
        script: |
          BUILD_NUMBER=$(($(app-store-connect get-latest-app-store-build-number "$APP_ID") + 1))
          flutter build ipa --release \
            --build-name=1.1.$BUILD_NUMBER \
            --build-number=$BUILD_NUMBER \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      # See the following link for details about email publishing - https://docs.codemagic.io/publishing-yaml/distribution/#email
      email:
        recipients:
          - powell.anthony.e@gmail.com
        notify:
          success: true # To receive a notification when a build succeeds
          failure: false # To not receive a notification when a build fails
      app_store_connect:
        auth: integration
        
        # Configuration related to TestFlight (optional)
        # Note: This action is performed during post-processing.
        submit_to_testflight: false
        # beta_groups: # Specify the names of beta tester groups that will get access to the build once it has passed beta review.
        #   - group name 1
        #   - group name 2

        # Configuration related to App Store (optional)
        # Note: This action is performed during post-processing.
        submit_to_app_store: true

  ios-publish-testflight-workflow:
    name: iOS Build and Publish to TestFlight Workflow
    instance_type: mac_mini_m1
    max_build_duration: 30
    integrations:
      app_store_connect: Power of One
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.powerofone.basketball
      flutter: stable
      xcode: latest # <-- set to specific version e.g. 14.3, 15.0 to avoid unexpected updates.
      cocoapods: default
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter analyze
        script: |
          flutter analyze
        ignore_failure: true
      # - name: Flutter unit tests
      #   script: |
      #     flutter test
      #   ignore_failure: true
      - name: Flutter build ipa and automatic versioning
        script: |
          BUILD_NUMBER=$(($(app-store-connect get-latest-testflight-build-number "$APP_ID") + 1))
          flutter build ipa --release \
            --build-name=1.1.$BUILD_NUMBER \
            --build-number=$BUILD_NUMBER \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      # See the following link for details about email publishing - https://docs.codemagic.io/publishing-yaml/distribution/#email
      email:
        recipients:
          - powell.anthony.e@gmail.com
        notify:
          success: true # To receive a notification when a build succeeds
          failure: false # To not receive a notification when a build fails
      app_store_connect:
        auth: integration
        
        # Configuration related to TestFlight (optional)
        # Note: This action is performed during post-processing.
        submit_to_testflight: true
        # beta_groups: # Specify the names of beta tester groups that will get access to the build once it has passed beta review.
        #   - group name 1
        #   - group name 2

        # Configuration related to App Store (optional)
        # Note: This action is performed during post-processing.
        submit_to_app_store: false