workflows:
  workflow1:
    name: Build
    max_build_duration: 60
    environment:
      vars:
          BUILD_VERSION: 1.1.7
          BUILD_NUMBER: 15
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - |
        # set up key.properties
        echo $FCI_KEYSTORE | base64 --decode > $FCI_KEYSTORE_PATH
        cat >> "$FCI_BUILD_DIR/android/key.properties" <<EOF
        storePassword=$FCI_KEYSTORE_PASSWORD
        keyPassword=$FCI_KEY_PASSWORD
        keyAlias=$FCI_KEY_ALIAS
        storeFile=/tmp/keystore.keystore
        EOF
      - name: Set up local properties
        script: echo "flutter.sdk=$HOME/programs/flutter" > "$FCI_BUILD_DIR/android/local.properties"
      - name: Flutter clean
        script: flutter clean
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build AAB with Flutter
        script: |
          flutter build appbundle --release
      - name: Install pods
        script: find . -name "Podfile" -execdir pod install \;
      - keychain initialize
      - app-store-connect fetch-signing-files "com.powerofone.basketball" --type IOS_APP_DEVELOPMENT
        --create
      - keychain add-certificates
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
      - name: Flutter build ipa
        script: |
           flutter build ipa --release \
            --export-options-plist ~/export_options.plist
    artifacts:
      - build/**/outputs/apk/**/*.apk
      - build/**/outputs/bundle/**/*.aab
      - build/**/outputs/**/mapping.txt
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - '*.snap'
      - build/windows/**/*.msix
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - powell.anthony.e@gmail.com
