on:
  push:
    branches:
      - 'main'
      - 'ios-release-candidate'
      - 'android-release-candidate'
      # for testing only
      - 'antpowell/github-build-actions'
  pull_request:
    branches:
      - 'main'
      - 'ios-release-candidate'
      - 'android-release-candidate'
name: 'Build & Release'
jobs:
  build-ios:
    name: Build & Release (iOS)
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        architecture: x64
    - run: flutter pub get
    # comment out until vp test are added
    # - run: flutter test
    - run: flutter build ios --release --no-codesign
  build-android:
    name: Build & Release (Android)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'
      - run: flutter clean
      - run: flutter pub get
      # comment out until vp test are added
      # - run: flutter test
      # - run: flutter build apk
      - run: flutter build appbundle -v

