on:
  push:
    branches:
      - 'main'
      - 'ios-release-candidate'
      - 'android-release-candidate'
  pull_request:
    branches:
      - 'main'
      - 'ios-release-candidate'
      - 'android-release-candidate'
name: 'Build & Release'
jobs:
  build-ios:
    name: Build & Release (iOS)
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        architecture: x64
    - run: flutter pub get
    # comment out until vp test are added
    # - run: flutter test
    - run: flutter build ios --release --no-codesign
  build-android:
    name: Build & Release (Android)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      # comment out until vp test are added
      # - run: flutter test
      - run: flutter build apk
      - run: flutter build appbundle

